rule("c++.meta")
    set_extensions(".h", ".hpp")
    on_config(function (target)
        import("xcpp.meta").setup(target)
    end)
    before_build(function (target)
        import("xcpp.meta").process(target)
    end)
    on_clean(function (target)
        import("xcpp.meta").clean(target)
    end)
